add updates

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,7 @@ jobs:
           COVERAGE: true
 
       - name: Verify LCOV Output
-        run: ls -la coverage && cat coverage/lcov.info
+        run: ls -la coverage && cat coverage/lcov.info || echo "❌ lcov.info NOT FOUND"
 
       - name: Code Climate Run before-test
         run: |
